### PR TITLE
Update yggdrasil-go version to 0.4.4

### LINKED ISSUE #31: Update to Yggdrasil 0.4.4
See https://github.com/yggdrasil-network/yggdrasil-go/releases/tag/v0.4.4

### PR DESCRIPTION
**Pull request by BratishkaErik**
Closes #31
Signed-off-by: Eric Joldasov <bratishkaerik@getgoogleoff.me>

### CODE REVIEW

**Comment by BratishkaErik** [comment]
https://github.com/yggdrasil-network/yggdrasil-go/commit/41b4bf69cfa7b0a2e0f7904867e49160f9283cea appveyor.yml has been changed to GitHub Actions

**Comment by wfleurant** [comment]
y'all should maintain openwrt section it would help keep everyone up tp date. and or, upstream this too

**Comment by zhoreeq** [comment]
@BratishkaErik @wfleurant bruh i'm scheduling a massive Yggdrasil update sprint this evening

**Comment by zhoreeq** [comment]
Updated Popura, will update openwrt package next

**Comment by wfleurant** [comment]
could you take ownership of the openwrt package homes

**Pull request closed without merging**
